Add controllers
AGolykh/java-shareit pull request #1
Opened 2023-04-24 13:16 UTC by AGolykh

2023-04-24 19:14 UTC, TomattmanYandex requested changes
1) При текущем подходе чаще всего внутри пакета отвечающего за конкретный функционал  не добавляется много подпакетов, т.е. пакет item и в нем сразу все что касается Item и контроллер и модели и дто без дополнительных подпакетов, сейчас очень тяжело проследить где что из-за этих подпакетов
2) зачем на id вешать ограничение на positive ? не надо придумывать ограничения которые не имеют смысла, иногда удобно исопльзовать например негативные id для тестовых значений, или значений проставленных системно
3) не обязательно добавлять аннотации валидации сразу и на дто и на модели, обычно взаимодействие в контроллерах идет только на уровне дто а потом уже они переводятся на уровне сервиса в классы можелей, и смыла классы моделей валидировать уже нету (но это станет понятнее к следующему спринту)

Отличная работа, основные вопросы к стилю кода

2023-04-24 19:14 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/StatusType.java
> +    WAITING(1L),
зачем нужен этот аргумент в виде id
Енамы в базе хранятся либо по значению, либо по такому числовому ключу, но тогда это индекс элемента в енаме, и лучше ипользовать тогда его

2023-04-24 19:14 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/StatusType.java
> +    StatusType(Long id) {
модификатор доступа

2023-04-24 19:14 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        Optional<User> result = userRepository.findById(userId);
так как мы используем optional то можно все свети примерно к такой конструкции
return userRepository.findById(userId).map(вызов метода по маппингу).orElseThrow(генерация ошибки);

2023-04-24 19:14 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
Почему бы не вынести в отдельный метод получение пользователя и уже не опшионала а сразу обьекта,  и чтобы метод прокидывал ошибку если не найдено, так как это будет происходить регулярно, то он пригодится, а вообще можно добавить зависимость от юзер сервиса и вызывать метод из него

Так же можно и с итемом, вметсо того чтобы отсюда делать вызывать метод из реползиториия и все проверять, сделать отдельрный метод который будет все это делать (сделать приватный метод который будет все это едлать и возвращать Item а тут вызывать его, а в методе получения по id вызывать его а после результат переводить в dto

2023-04-25 06:10 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        Optional<User> result = userRepository.findById(userId);
ЗАменил, там где возможно, остается вопрос, как логгировать при положительном результате?

2023-04-25 07:01 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
Готово

2023-04-25 07:02 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        Optional<User> result = userRepository.findById(userId);
Готово

2023-04-25 20:01 UTC, TomattmanYandex approved these changes
Принято

2023-05-05 12:32 UTC, merged