Add bookings
AGolykh/java-shareit pull request #2
Opened 2023-05-12 16:45 UTC by AGolykh

2023-05-13 14:38 UTC, TomattmanYandex requested changes
Привет, отличная работа коменты как обычно в коде

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handle(final ObjectNotFoundException e) {
Как много разных ошибок, кажется можно сделать меньше ошибок, и в зависимости от результата передавать их с разным сообщением (но это так, просто в глаза бросается но жить с этим можно)

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @Column(name = "ITEM_ID")
зачем в каждой таблице колонке id даавать разное имя, только будет усложнять работу с ней

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemFullDto.java
> +public class ItemFullDto {
ты уверен что необходимо такое количество DTO например эта содержит все поля, две последнии содержат одинаковый набор полей, но с разной валидацией на одно поле, кажется для того чтобы не путаться лучше иметь один обьект а id валидировать в сервисе, где он нужен или нет. Да и для всех случаев подойдет дто со всеми полями , просто некоторые из них будут null

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    if (itemFullDto.getOwner().getId().equals(userId)) {
Зачем нужна эта проверка, ведь мы искали где владелец  этот пользователь

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    ItemFullDto itemFullDto = ItemMapper.mapToFullDto(item);
возможно было бы лучше вынести все содержимое блока в отдельный метод, и вызывать его, читалось бы гораздо легче
даже просто благодаря имени метода было бы понятно что за действие тут происходит

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (result.getOwner().getId().equals(userId)) {
аналогично с предыдущим

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            result.setLastBooking(bookingRepository
и снова все те же действия что были в пердыдущем методе в отдельном блоке, если бы было в отдельном методе, то тут и там был бы вызов одного и того де метода, и поддерживать и рефакторить станет проще

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/dto/UserFullDto.java
> +public class UserFullDto {
тут еще больше бросается в глаза то, что дто почти одинаковые, стоит все же оставить только одну

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @GetMapping("/owner")
так в моей версии задания этот эндпоинт должен быть
GET /owner/bookings?state={state}
а по текущей реализации он будет 
/bookings/owner
если в вашем задании не так, просто оставь тут коммент

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Status status;
кстати обычно с енамами гораздо проще хранить в базе текстовое представление, так когда смотришь в саму базу видишь конкретное значение и не надо никакх маппингов, плюс изменение енама (добавление новых полей никак это не заденет)

2023-05-13 14:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingFullDto.java
> +public class BookingFullDto {
н тут то же что и во всех дто

2023-05-14 06:51 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @Column(name = "ITEM_ID")
Исправил ID и NAME столбцы

2023-05-14 06:53 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @GetMapping("/owner")
![image](https://github.com/AGolykh/java-shareit/assets/114491672/3f4387cb-bb0b-431f-b4de-4f3ac2dd7951)

У нас так

2023-05-14 06:54 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Status status;
Заменил на стринги

2023-05-14 07:45 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    if (itemFullDto.getOwner().getId().equals(userId)) {
Эта проверка нужна для этого условия
![image](https://github.com/AGolykh/java-shareit/assets/114491672/27dfce82-f026-4060-ab3d-4582eba5f1ba)

Вещи все юзеры могут посмотреть, но если юзер - владелец вещи, то он еще должен увидеть последнюю и следующую бронь

2023-05-15 07:20 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handle(final ObjectNotFoundException e) {
Убрал кастомные исключения, использую библиотечные

2023-05-15 07:45 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    ItemFullDto itemFullDto = ItemMapper.mapToFullDto(item);
Создание и добавление данных вынесено в отдельный метод

2023-05-15 07:45 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (result.getOwner().getId().equals(userId)) {
Создание и добавление данных вынесено в отдельный метод

2023-05-15 07:48 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            result.setLastBooking(bookingRepository
Создание и добавление данных вынесено в отдельный метод

2023-05-15 08:21 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/item/dto/ItemFullDto.java
> +public class ItemFullDto {
Сократил количество DTO, выходные дто оставил, придерживался такого принципа, если сущность вызывается непосредственно сама, то полный формат, если вызывается сущность в составе другой сущности, то краткий формат, что бы не засорят рекурсиями json

2023-05-15 08:21 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/user/dto/UserFullDto.java
> +public class UserFullDto {
Исправил

2023-05-15 08:23 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/booking/dto/BookingFullDto.java
> +public class BookingFullDto {
Тут дто не стал трогать, так как  иногда нужно вызывать букинг,  в котором прописаны данные предмета(без указания владельца) и букера, а иногда вызывается предмет, в котором прописан букинг в краткой форме, опять таки, что бы избегать рекурсий

2023-05-16 07:24 UTC, TomattmanYandex approved these changes
Принято

2023-05-16 08:30 UTC, merged