Add item requests
AGolykh/java-shareit pull request #3
Opened 2023-05-25 07:12 UTC by AGolykh

2023-05-30 08:50 UTC, TomattmanYandex requested changes
Привет, отличная работа, парочка мелких изменений и будет супер

2023-05-30 08:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        return itemRequestService.getByRequesterId(requesterId);
Запросы должны возвращаться в отсортированном порядке от более новых к более старым.
Но сортировку нигде в коде не уивдел

2023-05-30 08:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        return itemRequestService.getAll(requesterId, from, size);
Запросы должны возвращаться в отсортированном порядке от более новых к более старым.

2023-05-30 08:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +        itemRequest.setCreated(LocalDateTime.now());
это все же логика сервиса, маппинг это одно поле переводим в другое

2023-05-30 08:50 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +public class BookingControllerTest {
Тестовые классы располагаем там же где и тестируемые классы (в том же пакете) 
если надо разделить интеграционные тесты и юнит тесты
то к интеграционным можно добавить постфикс IT в конце
юнит тест BookingServiceTest
интеграционный BookingServiceIT

2023-05-30 08:50 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/integration/ItemRequestIntegrationTest.java
> +@SpringBootTest(properties = "spring.datasource.url = jdbc:h2:mem:test")
Второй вариант, 
создать в папке с тестами ресурсовую папку, и в нем сделать application.properties файл
те проперти что есть в тестовом, будут использованы из него, те которых нету, будут подтянуты из основного

2023-05-30 08:50 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/integration/ItemRequestIntegrationTest.java
> +    void getById_return1ItemRequestEveryTime_added2ItemRequests() {
стоило бы добавить тест на сохранение через сервис, да оно есть в подготовке, оно лучше добавить тест тоже

2023-05-30 09:19 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        return itemRequestService.getByRequesterId(requesterId);
itemRequestService.getByRequesterId теперь использует запросные методы с сортировкой

2023-05-30 09:20 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        return itemRequestService.getAll(requesterId, from, size);
метод itemRequestService.getAll использует приватный метод 
`    private PageRequest getPage(Integer from, Integer size) {
        if (size <= 0 || from < 0) {
            throw new IllegalArgumentException("Page size must not be less than one.");
        }
        return PageRequest.of(from / size, size, Sort.by("created").**descending**());
    }`

2023-05-30 10:12 UTC, AGolykh commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +public class BookingControllerTest {
изменена иерархия пакетов

2023-05-30 10:16 UTC, AGolykh commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +        itemRequest.setCreated(LocalDateTime.now());
установка даты и времени перенесена в сервис

2023-05-30 10:35 UTC, AGolykh commented on src/test/java/ru/practicum/shareit/integration/ItemRequestIntegrationTest.java
> +@SpringBootTest(properties = "spring.datasource.url = jdbc:h2:mem:test")
ввиду обучения создал папку ресурсов

2023-05-30 10:48 UTC, AGolykh commented on src/test/java/ru/practicum/shareit/integration/ItemRequestIntegrationTest.java
> +    void getById_return1ItemRequestEveryTime_added2ItemRequests() {
Добавлены тесты на создание сущностей

2023-05-31 11:14 UTC, TomattmanYandex approved these changes
Принято

2023-05-31 12:26 UTC, merged