Add docker
AGolykh/java-shareit pull request #4
Opened 2023-06-05 08:47 UTC by AGolykh

2023-06-06 09:44 UTC, TomattmanYandex requested changes
Привет, вроде как все отлично, пара мелких моментов на исправление есть

И да, из Dto в серверной части стоит удалить все валидирующие аннотации, ибо они там уже не нужны

2023-06-06 09:44 UTC, TomattmanYandex commented on docker-compose.yml
> +      - db
Гейтвей не должен зависеть от базы

2023-06-06 09:44 UTC, TomattmanYandex commented on server/src/main/java/ru/practicum/shareit/validators/StartEndDate.java
> +public @interface StartEndDate {
зачем нам здесь нужен валидатор, валидация проходит на стороне гейтвея

2023-06-06 10:00 UTC, AGolykh commented on docker-compose.yml
> +      - db
Зависимость убрана

2023-06-06 10:01 UTC, AGolykh commented on server/src/main/java/ru/practicum/shareit/validators/StartEndDate.java
> +public @interface StartEndDate {
Кастомный валидатор убран из сервера, как и все валидирующие аннотации из входных ДТО и контроллеров

2023-06-06 10:02 UTC, AGolykh commented on server/src/main/java/ru/practicum/shareit/validators/StartEndDate.java
> +public @interface StartEndDate {
Убраны (defaultValue) из аннотаций в контроллерах

2023-06-07 09:38 UTC, TomattmanYandex approved these changes
Принято

2023-06-07 09:41 UTC, merged